server.port : 8081

app :
  environment : production
  client :
    orderByName : true

spring.datasource :
  url : jdbc:hsqldb:file:db/xebia-boot
  driverClassName : org.hsqldb.jdbcDriver
  username : sa
  password :

security :
  user :
    name : xebia
    password : xebia
    role : USER,ADMIN

management.port : 8787

