#
# TODO 3.1 : Utiliser cette propriété pour changer le port du serveur en ligne de commande
#
#server.port : 8081

#
# TODO 3.4 : injecter la valeur app.enviromnent dans ClientService en utilisant @Value
#
app :
  environment : production
  #
  # TODO 3.5 : utiliser les @ConfigurationProperties pour gérer les configuration du service
  #
  #client :
    #orderByName : true

#
# TODO 2.1 : Configurer la datasource pour utiliser hsqldb
#
#spring.datasource :
#  url : jdbc:hsqldb:file:db/xebia-boot
#  driverClassName : org.hsqldb.jdbcDriver
#  username : sa
#  password :

#
# TODO 5.1 : Activer spring security

#
# TODO 4.1 : Changer le port des endpoints actuator

